"""empty message

Revision ID: 1da6f4ecaa6f
Revises: 7c27cec39a0e
Create Date: 2021-01-02 20:34:18.485019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da6f4ecaa6f'
down_revision = '7c27cec39a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('people')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
