"""empty message

Revision ID: 2a16dc432819
Revises: 8cd7b13e376e
Create Date: 2021-01-02 13:20:37.660568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a16dc432819'
down_revision = '8cd7b13e376e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('management')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management',
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.Column('admin_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('admin_id', name='pk_management')
    )
    # ### end Alembic commands ###
