"""empty message

Revision ID: 8cd7b13e376e
Revises: 2f3ea731ad41
Create Date: 2021-01-02 13:18:22.141722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd7b13e376e'
down_revision = '2f3ea731ad41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('admin_id', name=op.f('pk_management'))
    )
    op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.Column('admin_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('admin_id', name='pk_admins')
    )
    op.drop_table('management')
    # ### end Alembic commands ###
