"""empty message

Revision ID: bc5ddf12f771
Revises: 41a3e61bb720
Create Date: 2020-12-30 10:22:29.835116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5ddf12f771'
down_revision = '41a3e61bb720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_time', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_set_time'), ['set_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_set_time'))
        batch_op.drop_column('set_time')

    # ### end Alembic commands ###
