"""empty message

Revision ID: d475b7a76c28
Revises: bc5ddf12f771
Create Date: 2021-01-01 19:02:23.863602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd475b7a76c28'
down_revision = 'bc5ddf12f771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.VARCHAR(length=300), nullable=True))

    # ### end Alembic commands ###
